import { gql, useQuery } from "@apollo/client";
import { useState } from "react";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const GET_ALL_PRODUCT = gql`
  query AllProducts {
    products {
      createdAt
      description
      id
      name
      price
      publishedAt
      slug
      typeDrink
      updatedAt
      image {
        url
      }
    }
  }
`;

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState(true);
  const [showSecondaryMessage, setShowSecondaryMessage] = useState(false);
  const { data } = useQuery(GET_ALL_PRODUCT);
  console.log(data);

  const handleYesClick = () => {
    setIsModalOpen(false);
  };

  const handleNoClick = () => {
    setShowSecondaryMessage(true);
  };

  const handleBackClick = () => {
    setShowSecondaryMessage(false);
  };
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="w-full max-w-[1120px] flex flex-col mx-auto pb-12 px-4">
        <Header />
      </div>

      {isModalOpen && !showSecondaryMessage && (
        <div className="fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 flex items-center justify-center">
          <div className="bg-white p-8 rounded-lg text-center">
            <h2 className="text-xl mb-4 font-semibold">
              Você tem mais de 18 anos?
            </h2>
            <div className="flex justify-center">
              <button
                className="bg-blue-500 text-white px-4 py-2 mr-4 rounded"
                onClick={handleYesClick}
              >
                Sim
              </button>
              <button
                className="bg-red-500 text-white px-4 py-2 rounded"
                onClick={handleNoClick}
              >
                Não
              </button>
            </div>
          </div>
        </div>
      )}

      {showSecondaryMessage && (
        <div className="fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 flex items-center justify-center">
          <div className="bg-white p-8 rounded-lg text-center">
            <h2 className="text-xl mb-4 font-semibold">
              Você precisa ter 18 anos ou mais para consumir bebidas alcoólicas.
            </h2>
            <p className="text-base mb-4">
              Se você tem alguma dúvida ou deseja mais informações, entre em
              contato conosco:{" "}
              <a href="mailto:contato@budega92.com">contato@budega92.com</a>
            </p>
            <button
              className="bg-blue-500 text-white px-4 py-2 rounded"
              onClick={handleBackClick}
            >
              Voltar
            </button>
          </div>
        </div>
      )}

      <div className="flex flex-col">
        <h2 className="text-xl justify-center text-center mb-5 font-semibold">
          O que eu posso fazer no site da budega 92?
        </h2>

        <div className="mb-32 pb-10 grid mx-auto   lg:max-w-5xl lg:w-full lg:mb-0 lg:grid-cols-3 lg:text-left">
          <div className="group rounded-lg border mr-10 border-gray-300 p-4 hover:border-gray-300 hover:bg-gray-100 text-center">
            <h2 className="inline-block text-lg font-sans">Produtos</h2>
            <span>
              <p className="text-sm opacity-50">
                Aqui você pode encontrar todos os produtos vendidos na budega 92
              </p>
            </span>
          </div>

          <div className="group rounded-lg mr-10 border border-gray-300 p-4 hover:border-gray-300 hover:bg-gray-100 text-center">
            <h2 className="inline-block text-lg font-sans">Histórias</h2>
            <span>
              <p className="text-base opacity-50">
                Aqui você irá mergulhar nesse mundo, nosso fundador irá contar a
                você tudo sobre as melhores bebidas da região!
              </p>
            </span>
          </div>

          <div className="group rounded-lg border border-gray-300 p-4 hover:border-gray-300 hover:bg-gray-100 text-center">
            <h2 className="inline-block text-lg font-sans">
              Contéudos exclusivos
            </h2>
            <span>
              <p className="text-base opacity-50">
                Acompanhe nossa página e receba as novidades antes de todo mundo
              </p>
            </span>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
